### ISSUE TITLE
Better picture resolution

### ISSUE THREAD

**Issue by HaochenW** [wguo-research/scCancer#1]
I believe it is a excellent job. But it could be better if the picture has better resolution~

**Comment by wguo-research** [comment]
Thanks for your attention and suggestion! The plots in the pictures can also be found in our example reports, which have higher resolution. And the links of example reports can be found in the readme.

**Comment by wguo-research** [comment]
> I believe it is a excellent job. But it could be better if the picture has better resolution~

Thanks for your attention and suggestion! The plots in the pictures can also be found in our example reports, which have higher resolution. And the links of example reports can be found in the readme.
