### ISSUE TITLE
where are the code show on the document you post?

### ISSUE THREAD

**Issue by honghh2018** [wguo-research/scCancer#19]
Hi wguo and all,
    Firstly, Thanks to develop the great tools.
    The document you post on you scCancer homepage or wiki just showing the picture but code that generated the picture you had post.
    By the way, the code and a few data encounter 404 error from the interview. 
     I do not understand why the code just not showing along with the picture just like seurat tutorial did.
    I hope the code can be post and wish best work.

**Comment by wguo-research** [comment]
The codes are in [3. Quick start](https://github.com/wguo-research/scCancer/wiki/3.-Quick-start) section. For the 404 error, I think it may due to the network.

**Comment by honghh2018** [comment]
您好！已经收到邮件，祝好！                                    洪汉辉
