### ISSUE TITLE
Error in plotMarkerDistribution(sc): Failed as no clusters found!  Clustering must be set via 'setClusters' to find marker genes. 

### ISSUE THREAD

**Issue by honghh2018** [wguo-research/scCancer#20]
Hi @wguo,
     Thanks to develop the great tools for single cell cancer analysis.
      There some issue occured when runing the scCancer.
      The  function runScStatistics had show error as running on the step 5 like below info.
      4. plotMarkerDistribution(sc)
       5. stop("Failed as no clusters found!  Clustering must be set via 'setClusters' to find marker genes.") 
       The error indicate that whether matrix should be run into seurat and find the cluster or not ?
       Meanwhile,  i found your guide that post in the web https://github.com/wguo-research/scCancer/wiki/3.-Quick-start' had never exhibited the executed clustering before runing the  runScStatistics function.
      Addtionanlly, the  function runScStatistics workflow just import the data that ouput from 
 10x cellranger count like below picture and it should be clustering first or should some steps be execute first before runing  function runScStatistics ?. 
      
![image](https://user-images.githubusercontent.com/41668708/83623335-c923e500-a5c3-11ea-9a15-d0f3b22d2f82.png)

**Comment by wguo-research** [comment]
When did you install our package? You can reinstall the latest version and try it again. If the error continue, please contact me.
